version: "3"

services:
  web:
    container_name: node-demo
    build:
      context: ../
    volumes:
      - ../:/app
    command: bash -c " (yarn config set registry https://registry.npm.taobao.org) && (yarn config set sass-binary-site https://npm.taobao.org/mirrors/node-sass) && yarn && yarn build"
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ../dist:/usr/share/nginx/html
      - ./logs:/var/log/nginx
      - ./conf.d:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
