version: "3"

services:
  web:
    container_name: node-demo
    build:
      context: ../
    volumes:
      - ../:/app
    command: yarn build"
    user: "1000:1000"
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ../dist:/usr/share/nginx/html
      - ./logs:/var/log/nginx
      - ./conf.d:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
