version: "3"

services:
  web:
    container_name: vite
    build:
      context: ../
    ports:
      - "3000:3000"
    volumes:
      - ../:/app
    command: bash -c " (yarn config set registry https://registry.npm.taobao.org) && (yarn config set sass-binary-site https://npm.taobao.org/mirrors/node-sass) && yarn && yarn dev --host"
